// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WerkzeugverleihData;

namespace WerkzeugverleihData.Migrations
{
    [DbContext(typeof(WerkzeugverleihContext))]
    [Migration("20190401185945_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WerkzeugverleihData.Models.Checkout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("End");

                    b.Property<DateTime>("Start");

                    b.Property<int?>("UserID");

                    b.Property<int?>("WerkzeugID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("WerkzeugID");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("WerkzeugverleihData.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WerkzeugverleihData.Models.Werkzeug", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Werkzeugs");
                });

            modelBuilder.Entity("WerkzeugverleihData.Models.Checkout", b =>
                {
                    b.HasOne("WerkzeugverleihData.Models.User", "User")
                        .WithMany("Checkouts")
                        .HasForeignKey("UserID");

                    b.HasOne("WerkzeugverleihData.Models.Werkzeug", "Werkzeug")
                        .WithMany()
                        .HasForeignKey("WerkzeugID");
                });
#pragma warning restore 612, 618
        }
    }
}
